version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/circleci-demo-ermahgerd
    steps:
      - checkout
      - run:
          name: install ansible
          command: sudo pip install ansible
      - run:
          name: install rsync
          command: sudo apt install -y rsync
      - run:
          name: deploy via ansible
          command: ansible-playbook .circleci/deploy.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
